# Generated by Django 2.2.24 on 2022-03-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_signature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='pdf_file',
        ),
    ]
