# Generated by Django 3.2.16 on 2023-01-16 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_delete_highschool'),
        ('base', '0587_auto_20210603_1411'),
        ('osis_signature', '0002_remove_actor_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='actor',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='actor',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='actor',
            name='language',
            field=models.CharField(blank=True, choices=[('fr-be', 'French'), ('en', 'English')], default='', max_length=30, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='actor',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='actor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.person', verbose_name='Person'),
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('city', ''), ('email', ''), ('first_name', ''), ('institute', ''), ('language', ''), ('last_name', ''), ('country_id__isnull', True)), ('person__isnull', True), _connector='OR'), models.Q(('person__isnull', True), models.Q(('city', ''), ('email', ''), ('first_name', ''), ('institute', ''), ('language', ''), ('last_name', ''), ('country_id__isnull', True), _connector='OR'), _negated=True)), name='external_xor_person'),
        ),
    ]
